name: "Setup project"
description: "Sets up project and its dependencies"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v1
      name: Setup Bun

    # - uses: actions/setup-node@v3
    #   name: Setup Node.js
    #   with:
    #     node-version: ${{ env.NODE_VERSION }}

    - shell: bash
      name: Install dependencies
      run: |
        bun install --frozen-lockfile
